name: chess_vectors_flutter
description: Chess pieces vectors (movable and resizable) for Flutter.
version: 1.0.0
author: Laurent Bernabe <laurent.bernabe@gmail.com>
homepage: https://github.com/loloof64/chess_vectors_flutter

environment:
    sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
